// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'



show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
 // ...

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUQVwW9UwFMN2IP5SSBJp39w0wXs1X5P4',
    appId: '1:491560770910:android:3717fbdfd7936881d0c3cf',
    messagingSenderId: '491560770910',
    projectId: 'test-app-todo-48948',
    storageBucket: 'test-app-todo-48948.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP82n08xpLLEhKmLvNEssErVFqXQbksNo',
    appId: '1:491560770910:ios:8bf336b2302b612ed0c3cf',
    messagingSenderId: '491560770910',
    projectId: 'test-app-todo-48948',
    storageBucket: 'test-app-todo-48948.appspot.com',
    iosClientId:
        '491560770910-qb000ki7snqh8kp8cqpm71t0rrhgd2u8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myAppTodo',
  );
}
